# 使用Python官方镜像
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV STABLE_DIFFUSION_REPO="https://github.com/w-e-w/stablediffusion.git"

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    wget \
    git \
    python3.11 \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# 创建工作目录
WORKDIR /app

# 克隆仓库
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git .

# 下载启动脚本
RUN wget -q https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.sh && \
    chmod +x webui.sh


RUN echo '#!/bin/bash
export STABLE_DIFFUSION_REPO="https://github.com/w-e-w/stablediffusion.git"
./webui.sh 
"$@"
' > webui-user.sh && \
    chmod +x webui-user.sh
# 暴露端口
EXPOSE 7860

# 设置启动命令
CMD ["./webui.sh"]