FROM ubuntu:22.04

# 设置环境变量
ENV STABLE_DIFFUSION_REPO="https://github.com/w-e-w/stablediffusion.git"
ENV DEBIAN_FRONTEND=noninteractive
 

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    wget \
    git \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get update \
    && apt-get install -y \
    python3.11 \
    python3.11-venv \
    python3.11-dev \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 克隆仓库
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git .

RUN chmod +x webui.sh


EXPOSE 7860
CMD ["./webui.sh", "-f"]