
FROM nvidia/cuda:12.8.0-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# for China
# RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
#    sed -i 's#http://.*.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list


# 安装系统依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python-is-python3 python3-pip \
    python3-dev\
    python3-venv\
    git \
    libgl1 \
    libglib2.0-0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

    # 创建虚拟环境（文件夹名：xinference-env）
RUN python -m venv /opt/xinference-env

# 直接使用虚拟环境里的 pip 安装 xinference（不需要 source 激活）
RUN /opt/xinference-env/bin/pip install --upgrade pip && \
    /opt/xinference-env/bin/pip install xinference


# 设置工作目录
WORKDIR /root





CMD ["/opt/xinference-env/bin/xinference", "local", "--host", "0.0.0.0", "--port", "9997"]