FROM chatimage/chatchat:0.3.1.3-93e2c87-20240829
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

WORKDIR /root
RUN python -m venv /root/xinference
RUN /root/xinference/bin/pip install "xinference[all]"

EXPOSE 7861 8501 9997

ENTRYPOINT []