FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# for China
# RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
#    sed -i 's#http://.*.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list
# install supervisord
RUN apt update -y && apt install -y supervisor && \
    mkdir -p /var/log/supervisord && \
    mkdir -p /opt/supervisor && \
    apt clean 

# install system packages
RUN apt update -y && apt install -y \
        python3 python-is-python3 python3-pip \
        libgl1-mesa-glx \
        diffusers \
        ffmpeg \
        opencv-python \
        libglib2.0-0 \
        git aria2 && \
    apt clean

# install jupyter
RUN pip install jupyter && \
    pip install nvitop && \
    pip cache purge
COPY jupyter/jupyter.sh   /opt/supervisor/jupyter.sh
COPY jupyter/jupyter.conf /etc/supervisor/conf.d/jupyter.conf

# for China
# RUN python -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade pip && \
#     pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN cd /root && git clone https://github.com/comfyanonymous/ComfyUI && \
    cd ComfyUI && pip install -r requirements.txt

WORKDIR /root/ComfyUI

#Download comfyui-ltxvideo
RUN cd custom_nodes && git clone https://github.com/Lightricks/ComfyUI-LTXVideo.git comfyui-ltxvideo

#Download comfyui-videohelpersuite
RUN cd custom_nodes && git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git comfyui-videohelpersuite

#Download comfyui-manager
RUN cd custom_nodes && git clone https://github.com/ltdrdata/ComfyUI-Manager comfyui-manager

# Download the FP8 Quantized Model
RUN cd /root/ComfyUI/models/checkpoints/ && \
    aria2c -k 1M -s 10 -x 10 https://huggingface.co/Lightricks/LTX-Video/resolve/main/ltxv-13b-0.9.7-dev.safetensors -o ltxv-13b-0.9.7-dev.safetensors

# Download the Required CLIP Model
RUN cd /root/ComfyUI/models/clip/ && \
    aria2c -k 1M -s 10 -x 10 https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/text_encoders/t5xxl_fp16.safetensors -o t5xxl_fp16.safetensors


# Copy comfyui supervisor configuration
COPY comfyui/comfyui.sh         /opt/supervisor/comfyui.sh
COPY comfyui/comfyui.conf       /etc/supervisor/conf.d/comfyui.conf

#Copy ltx13b-i2v default workflow
COPY comfyui/ltxv-13b-i2v.json /root/ComfyUI/user/default/workflows/ltxv-13b-i2v.json

CMD  ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]

