FROM ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddlex-genai-vllm-server:latest
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1




CMD ["paddlex_genai_server", "--model_name", "PaddleOCR-VL-0.9B", "--host", "0.0.0.0", "--port", "8118", "--backend", "vllm"]